style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  ReturnCount:
    active: false
  ThrowsCount:
    active: false

complexity:
  LongParameterList:
    active: true
    ignoreDefaultParameters: true
    ignoreDataClasses: true
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Test
